### ISSUE TITLE
Multi-line formula RENDERING bug.

### ISSUE THREAD

**Issue by H-Lumos** [BMPixel/moffee#11]
Right markdown syntax used, wrong rendering output.
```
## this is a level 2 title

now, let's test formula feature, Maxwell's Equations are shown below:

$$
\nabla \cdot \vec B = 0 \\
\nabla \times \vec B = - \frac{\partial \vec E}{\partial t}
$$
```
Side preview on VSCode:
<img width="493" alt="image" src="https://github.com/user-attachments/assets/2449b4e9-a1f5-4fcd-afd2-a0e1b73e6a63">

After `moffee live .md`, wrong output:
<img width="539" alt="image" src="https://github.com/user-attachments/assets/a0a86d14-6031-4021-8b4f-d0ef06df03ee">

**Comment by BMPixel** [comment]
Thank you. I'll look into it. Maybe it's about configs for MathJax.

**Comment by BMPixel** [comment]
MathJax v3, which is used in moffee, [does not support double backslash](https://github.com/mathjax/MathJax/issues/2312) for new lines. Since MathJax is no longer mantained, I change to Ketax in [this commit](https://github.com/BMPixel/moffee/commit/551abf6556fbb4d36a8390c6f021feecb47b5e8b). It should be working now. Before next release, to apply the changes, please install moffee from the repo.
